version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: project_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      USE_POSTGRES: '1'
      POSTGRES_DB: project_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_DEBUG: '1'
      DJANGO_ALLOWED_HOSTS: '*'
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
